runtime: go112


# [STARTT env]
# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
        SENDGRID_API_KEY: ""
# [END env]